### ISSUE TITLE
add st_Blocks_new

### ISSUE THREAD

**Issue by rdemaria** [martinschwinzerl/sixtracklib#1]

**Comment by martinschwinzerl** [comment]
Fixed using commit https://github.com/martinschwinzerl/sixtracklib/commit/c9f3ce79ee6808eeeef336694516f89f432fa679

Added  NS(Blocks_new)() and NS(Blocks_delete)() functions.
The NS(Blocks_delete)() function is required to also free the NS(Blocks)* pointer - users should use new/delete  and  init/free in pairs 

Added minimal unit-test to tests/sixtracklib/common/test_blocks.cpp

Created https://github.com/martinschwinzerl/sixtracklib/issues/6 towards getting this (and everything else) documented
