### ISSUE TITLE
fix simple_drift_opencl.c device selection

### ISSUE THREAD

**Issue by rdemaria** [martinschwinzerl/sixtracklib#4]

**Comment by martinschwinzerl** [comment]
OpenCL Device selection based on NS(ClContext) should work as of commit [fd5fc0af](https://github.com/martinschwinzerl/sixtracklib/commit/209e99c90cecf15b5e1eaa3d2f7487822b49b36e) in both C and C++.

Please cf. [examples/c99/track_lhc_no_bb_opencl.c](https://github.com/martinschwinzerl/sixtracklib/blob/master/examples/c99/track_lhc_no_bb_opencl.c)
or [examples/cxx/track_lhc_no_bb_opencl.cpp](https://github.com/martinschwinzerl/sixtracklib/blob/master/examples/cxx/track_lhc_no_bb_opencl.cpp) for reference

Note: The simple_drift_opencl.c examples has been replaced by the more relevant examples above.
